#!/bin/bash

sudo apt install -y fish git git-lfs curl fish build-essential ubuntu-restricted-extras chromium-browser i3-wm i3status dconf-editor snapd \
    fonts-font-awesome rofi nautilus okular mc vim apt-transport-https ca-certificates curl software-properties-common sshpass python3 python-setuptools python-venv pygobject libtool libffi libjpg openssl autoconf bison swig glib2.0 portaudio19 mpg123 flac curl fann g++ jq &&

# flatpak
# sudo add-apt-repository ppa:alexlarsson/flatpak &&
# sublime
# wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add - &&
# echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list &&



 sudo snap install intellij-idea-community --classic --edge ; and
 sudo snap install datagrip --classic --edge ; and
 sudo snap install pycharm-professional --classic --edge ; and
 sudo snap install gitkraken
