#!/bin/bash

sudo apt install -y fish git git-lfs curl fish build-essential ubuntu-restricted-extras chromium-browser i3-wm i3status dconf-editor snapd \
    fonts-font-awesome rofi nautilus okular mc vim apt-transport-https ca-certificates curl software-properties-common &&

# flatpak
 sudo add-apt-repository ppa:alexlarsson/flatpak &&
# sublime
# wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add - &&
# echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list &&

curl -fsSL https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add - &&

 sudo apt-get update &&
 sudo apt-get install -y sublime-text flatpak &&

 sudo snap install intellij-idea-community --classic --edge &&
 sudo snap install datagrip --classic --edge &&
 sudo snap install pycharm-professional --classic --edge &&
 sudo snap install gitkraken
